# Generated by Django 3.0.4 on 2020-03-22 10:59

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagecaruselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
