# Generated by Django 3.0.4 on 2020-03-23 07:33

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_flexpage_featured_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='featured_media',
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add yor text', required=True))])), ('full_richtext', streams.blocks.RichtextBlock()), ('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Name', required=False)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_lenght=50, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True))])))])), ('cards_link', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_lenght=50, required=True)), ('link', wagtail.core.blocks.URLBlock(required=True))])))])), ('media', streams.blocks.TestMediaBlock(icon='media'))], blank=True, null=True),
        ),
    ]
